//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Cyborg_V._3_Black_Ops_II.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tool_Cyborg_V._3_Black_Ops_II.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1yy {
            get {
                object obj = ResourceManager.GetObject("1yy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _28170108_381307235674236_1269340887_o {
            get {
                object obj = ResourceManager.GetObject("28170108_381307235674236_1269340887_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alca_v2 {
            get {
                object obj = ResourceManager.GetObject("Alca_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alca_V3 {
            get {
                object obj = ResourceManager.GetObject("Alca_V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AntiFed {
            get {
                object obj = ResourceManager.GetObject("AntiFed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] arctic_v3 {
            get {
                object obj = ResourceManager.GetObject("arctic_v3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Army {
            get {
                object obj = ResourceManager.GetObject("Army", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] army_v4 {
            get {
                object obj = ResourceManager.GetObject("army_v4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Avalanger {
            get {
                object obj = ResourceManager.GetObject("Avalanger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Aviation_v1_5 {
            get {
                object obj = ResourceManager.GetObject("Aviation_v1_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BAREFACE_LEO {
            get {
                object obj = ResourceManager.GetObject("BAREFACE_LEO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BELGUIM {
            get {
                object obj = ResourceManager.GetObject("BELGUIM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Blazed_V1 {
            get {
                object obj = ResourceManager.GetObject("Blazed_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Blue_Sky_V1 {
            get {
                object obj = ResourceManager.GetObject("Blue_Sky_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Blue_Sky_V2 {
            get {
                object obj = ResourceManager.GetObject("Blue_Sky_V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bossam_V3 {
            get {
                object obj = ResourceManager.GetObject("Bossam_V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bossam_V4 {
            get {
                object obj = ResourceManager.GetObject("Bossam_V4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bossam_V5 {
            get {
                object obj = ResourceManager.GetObject("Bossam_V5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossamV1 {
            get {
                object obj = ResourceManager.GetObject("BossamV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BossamV6 {
            get {
                object obj = ResourceManager.GetObject("BossamV6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bounce_Mod {
            get {
                object obj = ResourceManager.GetObject("Bounce_Mod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Breaking_Earth_V1_1 {
            get {
                object obj = ResourceManager.GetObject("Breaking_Earth_V1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CacheCache1 {
            get {
                object obj = ResourceManager.GetObject("CacheCache1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Cairo_PAtch {
            get {
                object obj = ResourceManager.GetObject("Cairo_PAtch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Caked_UP {
            get {
                object obj = ResourceManager.GetObject("Caked_UP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Caked_Up_Has_Swag {
            get {
                object obj = ResourceManager.GetObject("Caked_Up_Has_Swag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Capofication_V2 {
            get {
                object obj = ResourceManager.GetObject("Capofication_V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Closing_Time_v1 {
            get {
                object obj = ResourceManager.GetObject("Closing_Time_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Code_Green {
            get {
                object obj = ResourceManager.GetObject("Code_Green", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Codeine_Crazy_Official_Release {
            get {
                object obj = ResourceManager.GetObject("Codeine_Crazy_Official_Release", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CodeMods_v1 {
            get {
                object obj = ResourceManager.GetObject("CodeMods_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Confusion {
            get {
                object obj = ResourceManager.GetObject("Confusion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Corrupted_v3 {
            get {
                object obj = ResourceManager.GetObject("Corrupted_v3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Corrupted_v3_BETA_1_5 {
            get {
                object obj = ResourceManager.GetObject("Corrupted_v3_BETA_1_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Creation_V1_Beta {
            get {
                object obj = ResourceManager.GetObject("Creation_V1_Beta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Crisis {
            get {
                object obj = ResourceManager.GetObject("Crisis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] crusher {
            get {
                object obj = ResourceManager.GetObject("crusher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Crusher11 {
            get {
                object obj = ResourceManager.GetObject("Crusher11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CyanEdition {
            get {
                object obj = ResourceManager.GetObject("CyanEdition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CyborgV1 {
            get {
                object obj = ResourceManager.GetObject("CyborgV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Daniel_Wasa {
            get {
                object obj = ResourceManager.GetObject("Daniel_Wasa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dark_Moon_V1 {
            get {
                object obj = ResourceManager.GetObject("Dark_Moon_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dark_Shadows_v1 {
            get {
                object obj = ResourceManager.GetObject("Dark_Shadows_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Death_Cry_V1_BETA {
            get {
                object obj = ResourceManager.GetObject("Death_Cry_V1_BETA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DeathRun {
            get {
                object obj = ResourceManager.GetObject("DeathRun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Deep_ocean_v1 {
            get {
                object obj = ResourceManager.GetObject("Deep_ocean_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] deeznutzv1 {
            get {
                object obj = ResourceManager.GetObject("deeznutzv1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Degeneration_v1_1_BETA {
            get {
                object obj = ResourceManager.GetObject("Degeneration_v1_1_BETA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Delusion {
            get {
                object obj = ResourceManager.GetObject("Delusion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Destinition {
            get {
                object obj = ResourceManager.GetObject("Destinition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Destiny_By_Enston {
            get {
                object obj = ResourceManager.GetObject("Destiny_By_Enston", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DiizyMoDz_v1 {
            get {
                object obj = ResourceManager.GetObject("DiizyMoDz_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DMT_V1 {
            get {
                object obj = ResourceManager.GetObject("DMT_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dreadnought_V3 {
            get {
                object obj = ResourceManager.GetObject("Dreadnought_V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dreadnought_V4 {
            get {
                object obj = ResourceManager.GetObject("Dreadnought_V4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dynamic_v2 {
            get {
                object obj = ResourceManager.GetObject("Dynamic_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dynamic_V3_1 {
            get {
                object obj = ResourceManager.GetObject("Dynamic_V3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dynamic_V3_3 {
            get {
                object obj = ResourceManager.GetObject("Dynamic_V3_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EB_Game {
            get {
                object obj = ResourceManager.GetObject("EB_Game", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ELeGanCe_Patch {
            get {
                object obj = ResourceManager.GetObject("ELeGanCe_Patch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ELeGanCe_v3 {
            get {
                object obj = ResourceManager.GetObject("ELeGanCe_v3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Elegance_V5 {
            get {
                object obj = ResourceManager.GetObject("Elegance_V5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EnCoReV2_3_BETA {
            get {
                object obj = ResourceManager.GetObject("EnCoReV2_3_BETA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] enslaved {
            get {
                object obj = ResourceManager.GetObject("enslaved", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ERUPTIONV2 {
            get {
                object obj = ResourceManager.GetObject("ERUPTIONV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Escalation_v1 {
            get {
                object obj = ResourceManager.GetObject("Escalation_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Exotic_V1 {
            get {
                object obj = ResourceManager.GetObject("Exotic_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Exotic_V2_BETA {
            get {
                object obj = ResourceManager.GetObject("Exotic_V2_BETA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExoTiQueModz {
            get {
                object obj = ResourceManager.GetObject("ExoTiQueModz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExoTiQueModz__OldModz95 {
            get {
                object obj = ResourceManager.GetObject("ExoTiQueModz__OldModz95", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Experience {
            get {
                object obj = ResourceManager.GetObject("Experience", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Exploit_V1 {
            get {
                object obj = ResourceManager.GetObject("Exploit_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Explosive {
            get {
                object obj = ResourceManager.GetObject("Explosive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Extinct_s_S_D {
            get {
                object obj = ResourceManager.GetObject("Extinct_s_S_D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Extincts {
            get {
                object obj = ResourceManager.GetObject("Extincts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FenixV5 {
            get {
                object obj = ResourceManager.GetObject("FenixV5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ferrox_V1 {
            get {
                object obj = ResourceManager.GetObject("ferrox_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlamezV1 {
            get {
                object obj = ResourceManager.GetObject("FlamezV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Floater_Game {
            get {
                object obj = ResourceManager.GetObject("Floater_Game", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Floor_Lave_Game {
            get {
                object obj = ResourceManager.GetObject("Floor_Lave_Game", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Free_All {
            get {
                object obj = ResourceManager.GetObject("Free_All", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FREEFALL {
            get {
                object obj = ResourceManager.GetObject("FREEFALL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Frosty_V1 {
            get {
                object obj = ResourceManager.GetObject("Frosty_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FroZ_v1 {
            get {
                object obj = ResourceManager.GetObject("FroZ_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FroZ_v2 {
            get {
                object obj = ResourceManager.GetObject("FroZ_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fuck_Sony_v3 {
            get {
                object obj = ResourceManager.GetObject("Fuck_Sony_v3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Game__Nuketown_Survival {
            get {
                object obj = ResourceManager.GetObject("Game__Nuketown_Survival", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Game_Border_Patrol {
            get {
                object obj = ResourceManager.GetObject("Game_Border_Patrol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Game_Dodgeball {
            get {
                object obj = ResourceManager.GetObject("Game_Dodgeball", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Game_Prison_Break {
            get {
                object obj = ResourceManager.GetObject("Game_Prison_Break", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Game_Superman_1v1 {
            get {
                object obj = ResourceManager.GetObject("Game_Superman_1v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Game_Tricky_Myers {
            get {
                object obj = ResourceManager.GetObject("Game_Tricky_Myers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Genesis {
            get {
                object obj = ResourceManager.GetObject("Genesis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GermanModzHD {
            get {
                object obj = ResourceManager.GetObject("GermanModzHD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GoldenGun {
            get {
                object obj = ResourceManager.GetObject("GoldenGun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GreenGoblin {
            get {
                object obj = ResourceManager.GetObject("GreenGoblin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Haunted {
            get {
                object obj = ResourceManager.GetObject("Haunted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Haunted1 {
            get {
                object obj = ResourceManager.GetObject("Haunted1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HexyModz_Private_Patch_v2 {
            get {
                object obj = ResourceManager.GetObject("HexyModz_Private_Patch_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hide_and_Seek {
            get {
                object obj = ResourceManager.GetObject("Hide_and_Seek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HostOnly_s_Private {
            get {
                object obj = ResourceManager.GetObject("HostOnly_s_Private", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HostOnlys_Private {
            get {
                object obj = ResourceManager.GetObject("HostOnlys_Private", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HostOnlys_Trickshot {
            get {
                object obj = ResourceManager.GetObject("HostOnlys_Trickshot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hunaveli {
            get {
                object obj = ResourceManager.GetObject("Hunaveli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hundergame {
            get {
                object obj = ResourceManager.GetObject("Hundergame", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hunger_Games {
            get {
                object obj = ResourceManager.GetObject("Hunger_Games", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hydro {
            get {
                object obj = ResourceManager.GetObject("hydro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Iconic {
            get {
                object obj = ResourceManager.GetObject("Iconic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Illuison_V1 {
            get {
                object obj = ResourceManager.GetObject("Illuison_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IMT_V2 {
            get {
                object obj = ResourceManager.GetObject("IMT_V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] INFINITI {
            get {
                object obj = ResourceManager.GetObject("INFINITI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] JiggyMenuV4_2 {
            get {
                object obj = ResourceManager.GetObject("JiggyMenuV4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] JR_JS_V5 {
            get {
                object obj = ResourceManager.GetObject("JR_JS_V5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] JR_JS_V6 {
            get {
                object obj = ResourceManager.GetObject("JR_JS_V6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Legend {
            get {
                object obj = ResourceManager.GetObject("Legend", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Legends_Curse_V1_Beta_2 {
            get {
                object obj = ResourceManager.GetObject("Legends_Curse_V1_Beta_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lol2b {
            get {
                object obj = ResourceManager.GetObject("lol2b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lost_Memories_Love {
            get {
                object obj = ResourceManager.GetObject("Lost_Memories_Love", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LoveOrHatebyxKraveModz {
            get {
                object obj = ResourceManager.GetObject("LoveOrHatebyxKraveModz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Luckyshot {
            get {
                object obj = ResourceManager.GetObject("Luckyshot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lyberta_V2 {
            get {
                object obj = ResourceManager.GetObject("Lyberta_V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mario_Kart {
            get {
                object obj = ResourceManager.GetObject("Mario_Kart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Masacre {
            get {
                object obj = ResourceManager.GetObject("Masacre", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Masacre_v1_zomboe {
            get {
                object obj = ResourceManager.GetObject("Masacre_v1_zomboe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Matrix_Trickshot {
            get {
                object obj = ResourceManager.GetObject("Matrix_Trickshot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://anonfile.com/S8c5Tab2ba/API_DDOS_by_KATRiX.rar
        ///______________________
        ///
        ///TUTORIEL:
        ///
        ///1- Tout d&apos;abord, vous devez upload le fichier &quot;testing.c&quot; ainsi que le fichier &quot;list.txt&quot; dans root.
        ///
        ///2- Ensuite, vous devez taper toutes les commandes qui se trouvent dans &quot;commandes.txt&quot; dans votre Linux.
        ///C&apos;est-à-dire:
        ///
        ///yum install httpd mod_ssl
        ////sbin/chkconfig httpd on
        ///yum install php-mysql php-devel php-gd php-pecl-memcache php-pspell php-snmp php-xmlrpc php-xml
        ////usr/sbin/apachectl restart
        ///yum install [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mettre_api {
            get {
                return ResourceManager.GetString("mettre_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mod_Menu_xTvxyv_1 {
            get {
                object obj = ResourceManager.GetObject("Mod_Menu_xTvxyv_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ModeMenuFDP {
            get {
                object obj = ResourceManager.GetObject("ModeMenuFDP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MWS_Menu {
            get {
                object obj = ResourceManager.GetObject("MWS_Menu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Night_v1 {
            get {
                object obj = ResourceManager.GetObject("Night_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NinjaModzv1 {
            get {
                object obj = ResourceManager.GetObject("NinjaModzv1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Nyctophilia {
            get {
                object obj = ResourceManager.GetObject("Nyctophilia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] oCmKs_4_Lifes_Private_Patch {
            get {
                object obj = ResourceManager.GetObject("oCmKs_4_Lifes_Private_Patch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Official_Project_Hiqh_v1 {
            get {
                object obj = ResourceManager.GetObject("Official_Project_Hiqh_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OldLastV1 {
            get {
                object obj = ResourceManager.GetObject("OldLastV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Original_Zombieland_Game {
            get {
                object obj = ResourceManager.GetObject("Original_Zombieland_Game", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Overdrive_v1 {
            get {
                object obj = ResourceManager.GetObject("Overdrive_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Parcour {
            get {
                object obj = ResourceManager.GetObject("Parcour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Parcour11 {
            get {
                object obj = ResourceManager.GetObject("Parcour11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlasmaMods_V3 {
            get {
                object obj = ResourceManager.GetObject("PlasmaMods_V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Predator_v1_3 {
            get {
                object obj = ResourceManager.GetObject("Predator_v1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Predator_v2 {
            get {
                object obj = ResourceManager.GetObject("Predator_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Predator_v3 {
            get {
                object obj = ResourceManager.GetObject("Predator_v3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Predator_v6_51 {
            get {
                object obj = ResourceManager.GetObject("Predator_v6_51", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Dream {
            get {
                object obj = ResourceManager.GetObject("Project_Dream", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Escape_V3 {
            get {
                object obj = ResourceManager.GetObject("Project_Escape_V3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Hiqh_v1 {
            get {
                object obj = ResourceManager.GetObject("Project_Hiqh_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Hydra {
            get {
                object obj = ResourceManager.GetObject("Project_Hydra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Iconic {
            get {
                object obj = ResourceManager.GetObject("Project_Iconic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Lemon_v1 {
            get {
                object obj = ResourceManager.GetObject("Project_Lemon_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Lethal_v2 {
            get {
                object obj = ResourceManager.GetObject("Project_Lethal_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Old {
            get {
                object obj = ResourceManager.GetObject("Project_Old", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Reeko_v2 {
            get {
                object obj = ResourceManager.GetObject("Project_Reeko_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Smash_V2 {
            get {
                object obj = ResourceManager.GetObject("Project_Smash_V2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Snow_V1 {
            get {
                object obj = ResourceManager.GetObject("Project_Snow_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Stoner_v1 {
            get {
                object obj = ResourceManager.GetObject("Project_Stoner_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_TCM_V1 {
            get {
                object obj = ResourceManager.GetObject("Project_TCM_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Ultimate {
            get {
                object obj = ResourceManager.GetObject("Project_Ultimate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Unity {
            get {
                object obj = ResourceManager.GetObject("Project_Unity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Unlimited_v1_5_4 {
            get {
                object obj = ResourceManager.GetObject("Project_Unlimited_v1_5_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Untlimited_v1_4_2 {
            get {
                object obj = ResourceManager.GetObject("Project_Untlimited_v1_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_X {
            get {
                object obj = ResourceManager.GetObject("Project_X", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Project_Zombee {
            get {
                object obj = ResourceManager.GetObject("Project_Zombee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectAqua {
            get {
                object obj = ResourceManager.GetObject("ProjectAqua", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectExcellence {
            get {
                object obj = ResourceManager.GetObject("ProjectExcellence", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectFroZv1 {
            get {
                object obj = ResourceManager.GetObject("ProjectFroZv1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectFroZv2 {
            get {
                object obj = ResourceManager.GetObject("ProjectFroZv2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectHunaveli {
            get {
                object obj = ResourceManager.GetObject("ProjectHunaveli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Projecticonic {
            get {
                object obj = ResourceManager.GetObject("Projecticonic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectIlluminati {
            get {
                object obj = ResourceManager.GetObject("ProjectIlluminati", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectLemonv1 {
            get {
                object obj = ResourceManager.GetObject("ProjectLemonv1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectMellow {
            get {
                object obj = ResourceManager.GetObject("ProjectMellow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectUnity {
            get {
                object obj = ResourceManager.GetObject("ProjectUnity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectWaves {
            get {
                object obj = ResourceManager.GetObject("ProjectWaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProjectWezarq {
            get {
                object obj = ResourceManager.GetObject("ProjectWezarq", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] projetescape {
            get {
                object obj = ResourceManager.GetObject("projetescape", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PS3DOWN_FR_V4 {
            get {
                object obj = ResourceManager.GetObject("PS3DOWN_FR_V4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Purlple_Kuch_v4 {
            get {
                object obj = ResourceManager.GetObject("Purlple_Kuch_v4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Purple_Dragon {
            get {
                object obj = ResourceManager.GetObject("Purple_Dragon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PurpleEdition {
            get {
                object obj = ResourceManager.GetObject("PurpleEdition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rawdog {
            get {
                object obj = ResourceManager.GetObject("Rawdog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RDC_V6_7 {
            get {
                object obj = ResourceManager.GetObject("RDC_V6_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rebelv1 {
            get {
                object obj = ResourceManager.GetObject("rebelv1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Reblunted {
            get {
                object obj = ResourceManager.GetObject("Reblunted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Reborn_v1 {
            get {
                object obj = ResourceManager.GetObject("Reborn_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Red_Rooster_V1_2 {
            get {
                object obj = ResourceManager.GetObject("Red_Rooster_V1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Red_Tear_v1 {
            get {
                object obj = ResourceManager.GetObject("Red_Tear_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Red_Tear_v2 {
            get {
                object obj = ResourceManager.GetObject("Red_Tear_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Red_Tear_v2_1 {
            get {
                object obj = ResourceManager.GetObject("Red_Tear_v2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RedDotCity_v2 {
            get {
                object obj = ResourceManager.GetObject("RedDotCity_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RedEdition {
            get {
                object obj = ResourceManager.GetObject("RedEdition", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Redemption_V1_8 {
            get {
                object obj = ResourceManager.GetObject("Redemption_V1_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Revolution {
            get {
                object obj = ResourceManager.GetObject("Revolution", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ride_My_BicycleV2 {
            get {
                object obj = ResourceManager.GetObject("Ride_My_BicycleV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sex_Game {
            get {
                object obj = ResourceManager.GetObject("Sex_Game", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Silent_Menu_v1 {
            get {
                object obj = ResourceManager.GetObject("Silent_Menu_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Silent_Menu_v1_8 {
            get {
                object obj = ResourceManager.GetObject("Silent_Menu_v1_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Silent_Shadow {
            get {
                object obj = ResourceManager.GetObject("Silent_Shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sky_High_v2_new_menu {
            get {
                object obj = ResourceManager.GetObject("Sky_High_v2_new_menu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Slenderman {
            get {
                object obj = ResourceManager.GetObject("Slenderman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Snakemodz1 {
            get {
                object obj = ResourceManager.GetObject("Snakemodz1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Space_Bound_v1 {
            get {
                object obj = ResourceManager.GetObject("Space_Bound_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Space_Bound_v1_SML {
            get {
                object obj = ResourceManager.GetObject("Space_Bound_v1_SML", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SS_Billcam_CONSUMER_EDITION_1 {
            get {
                object obj = ResourceManager.GetObject("SS_Billcam_CONSUMER_EDITION_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SSM_Millennium {
            get {
                object obj = ResourceManager.GetObject("SSM_Millennium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SSM_The_Cypher {
            get {
                object obj = ResourceManager.GetObject("SSM_The_Cypher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Superman_Game {
            get {
                object obj = ResourceManager.GetObject("Superman_Game", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Synthbreaker {
            get {
                object obj = ResourceManager.GetObject("Synthbreaker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Synthbreaker_v1 {
            get {
                object obj = ResourceManager.GetObject("Synthbreaker_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Syzygyv2 {
            get {
                object obj = ResourceManager.GetObject("Syzygyv2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Syzygyv2compiled {
            get {
                object obj = ResourceManager.GetObject("Syzygyv2compiled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] The_Golden_Gun {
            get {
                object obj = ResourceManager.GetObject("The_Golden_Gun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TheCrusher {
            get {
                object obj = ResourceManager.GetObject("TheCrusher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TheLastOreoV2 {
            get {
                object obj = ResourceManager.GetObject("TheLastOreoV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TheLastOreoV3 {
            get {
                object obj = ResourceManager.GetObject("TheLastOreoV3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TheLastOreoV3Stealth {
            get {
                object obj = ResourceManager.GetObject("TheLastOreoV3Stealth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TnTRun {
            get {
                object obj = ResourceManager.GetObject("TnTRun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TogetherPrivate_Patch {
            get {
                object obj = ResourceManager.GetObject("TogetherPrivate_Patch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WhiteWater_v5_5 {
            get {
                object obj = ResourceManager.GetObject("WhiteWater_v5_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xePixTvx_s_Private_Menu {
            get {
                object obj = ResourceManager.GetObject("xePixTvx_s_Private_Menu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XPLobby {
            get {
                object obj = ResourceManager.GetObject("XPLobby", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Zario_v1_0 {
            get {
                object obj = ResourceManager.GetObject("Zario_v1_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZombieLand {
            get {
                object obj = ResourceManager.GetObject("ZombieLand", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Toxic_v1 { get; set; }

        public static byte[] Unbound_User_v4 { get; set; }

        public static byte[] Velocity_V2 { get; set; }

        public static byte[] VerificationModz { get; set; }

        public static byte[] Waterfall_v1 { get; set; }

        public static byte[] Waves { get; set; }

        public static byte[] Unreleased { get; set; }

        public static byte[] Unknown_Modding { get; set; }

        public static byte[] VelocityV2 { get; set; }

        public static byte[] trojan { get; set; }
    }
}
